console.log(Math.PI)
console.log(Math.E)
console.log(Math.ceil(10.4))
console.log(Math.floor(10.4))
console.log(Math.round(9.4))
console.log(Math.trunc(8.6))
console.log(Math.pow(2,3))
console.log(Math.sqrt(49))
console.log(Math.cbrt(216))
console.log(Math.abs(-5))
console.log(Math.log10(10000))
console.log(Math.log2(16))
//console.log(Math.log()) returns base e of a number
console.log(Math.min(3,4,5))
console.log(Math.max(0,1,2))

console.log(Math.sin(0))
console.log(Math.cos(0))
console.log(Math.tan(0))
console.log(Math.random((0,10))*10)